package models

import (
	"database/sql"
	"time"
)

//内存对齐
type Post struct {
	ID         int64     `json:"id,string" db:"post_id"`                           // 帖子id
	AuthorID   int64     `json:"author_id,string" db:"author_id"`                  // 作者id
	TopicID    int64     `json:"topic_id,string" db:"topic_id" binding:"required"` // 社区id
	Status     int32     `json:"status" db:"status"`                               // 帖子状态
	Title      string    `json:"title" db:"title" binding:"required"`              // 帖子标题
	Content    string    `json:"content" db:"content" binding:"required"`          // 帖子内容
	CreateTime time.Time `json:"create_time" db:"create_time"`                     // 帖子创建时间
	PostKey    string    `json:"post_key"db:"post_key"`                            //帖子的哈希值
}

type GetPostByKey struct {
	ID       int64          `json:"id,string" db:"post_id"`                           // 帖子id
	AuthorID int64          `json:"author_id,string" db:"author_id"`                  // 作者id
	Title    sql.NullString `json:"title" db:"title" binding:"required"`              // 帖子标题
	Content  string         `json:"content" db:"content" binding:"required"`          // 帖子内容
	TopicID  int64          `json:"topic_id,string" db:"topic_id" binding:"required"` // 社区id
}

type ResponseCreate struct {
	ID       int64 `json:"id,string" db:"post_id"`                           // 帖子id
	AuthorID int64 `json:"author_id,string" db:"author_id"`                  // 作者id
	TopicID  int64 `json:"topic_id,string" db:"topic_id" binding:"required"` // 社区id
	Status   int32 `json:"status" db:"status"`                               // 帖子状态
	//Title      string    `json:"title" db:"title" binding:"required"`              // 帖子标题
	Content    string    `json:"content" db:"content" binding:"required"` // 帖子内容
	CreateTime time.Time `json:"create_time" db:"create_time"`            // 帖子创建时间
	PostKey    string    `json:"post_key"db:"post_key"`                   //帖子的哈希值
}
type AutoGenerated []struct {
	Postkey string `json:"postkey"`
}

type GetPostwithRes struct {
	ID       int64 `json:"id,string" db:"post_id"`          // 帖子id
	AuthorID int64 `json:"author_id,string" db:"author_id"` // 作者id

	//将NULL值赋给title结构体字段时出现了错误。Go语言中将NULL值赋给字符串类型的字段时会出现这个错误。:
	// {"error": "sql: Scan error on column index 2, name \"title\": converting NULL to string is unsupported"}
	//
	Title   sql.NullString `json:"title" db:"title" binding:"required"`              // 帖子标题
	Content string         `json:"content" db:"content" binding:"required"`          // 帖子内容
	TopicID int64          `json:"topic_id,string" db:"topic_id" binding:"required"` // 社区id
}
