package main

import "fmt"

type AutoGenerated []struct {
	Postkey string `json:"postkey"`
}

func main() {
	autoGenerated := &AutoGenerated{
		{Postkey: "value1"},
		{Postkey: "value2"},
		{Postkey: "value3"},
	}
	for _, item := range *autoGenerated {
		fmt.Println(item.Postkey)
	}
}
